
#ifndef __LOWLAT_CONV_DEFINES_H
#define __LOWLAT_CONV_DEFINES_H

#define LLC_BUFFERSIZE_TCP 1024
#define LLC_BUFFERSIZE_UDP 1024
#define LLC_BUFFERSIZE_SIO 1024

#define LLC_SOCKET_HAS_RECEIVED_EOF -1
#define LLC_NO_DATA_TRANSFER_FROM_SOCKET -2
#define LLC_NO_DATA_TRANSFER_TO_SOCKET -3
#define LLC_SOCKET_IS_NOT_INITIALISED -4
#define LLC_NO_MORE_CHANNELS_AVAILABLE -5
#define LLC_CHANNEL_NOT_AVAILABLE -6
#define LLC_SOCKET_IS_NOT_AVAILABLE -7
#define LLC_NO_SENDER_SPECIFIED -8
#define LLC_NO_RECEIVER_SPECIFIED -9
#define LLC_TCP_SOCKET_IS_LISTENING -10
#define LLC_INSUFFICIENT_BUFFER_SPACE -11
#define LLC_TCP_SOCKET_NOT_LISTENING -12

#define LLC_PROBLEM_WHILE_SELECTING_FDS 1000
#define LLC_NO_BUFFER_AVAILABLE 1010
#define LLC_UNABLE_TO_SET_INPUT_SPEED 1020
#define LLC_UNABLE_TO_SET_OUTPUT_SPEED 1030
#define LLC_SOCKET_DESCRIPTOR_INVALID 1040
#define LLC_INVALID_IO_CHANNEL_USED 1050
#define LLC_UNREGISTERED_FILE_DESCRIPTOR 1060
#define LLC_PROBLEM_WHILE_REMOVING_FDS 1070
#define LLC_EXCEPTION_PROCESSING_FDS 1080
#define LLC_RULESET_EXHAUSTED 1200
#define LLC_SPURIOUS_INPUT 1220
#define LLC_SYNTAX_ERROR 1240
#define LLC_RULE_STACK_EXHAUSTED 1250
#define LLC_OPERAND_STACK_EXHAUSTED 1280
#define LLC_INVALID_NMEA_HEADER 1350
#define LLC_OPERAND_LENGTH_EXCEEDED 1400
#define LLC_INVALID_CHANNEL_INDEX 1500
#define LLC_NO_INPUT_CHANNEL_AVAILABLE 1502
#define LLC_NO_OUTPUT_CHANNEL_AVAILABLE 1504
#define LLC_INPUT_CHANNEL_EXHAUSTED 1510
#define LLC_DUPLICATE_CHANNEL_ASSIGNMENT 1515
#define LLC_SIGNAL_CAPACITY_EXHAUSTED 1520
#define LLC_MESSAGE_CAPACITY_EXHAUSTED 1530
#define LLC_NETWORK_HANDLE_MISSING 1540
#define LLC_NO_SIGNALS_FOUND 1550
#define LLC_NO_MESSAGES_FOUND 1560
#define LLC_ILLEGAL_MESSAGE_HANDLE 1570
#define LLC_NO_MORE_TIMER_AVAILABLE 1600
#define LLC_ILLEGAL_INTERVAL_LENGTH 1610
#define LLC_NO_TIMERS_REGISTERED 1620
#define LLC_NO_EVENTS_PENDING 1630
#define LLC_ILLEGAL_TIMER_INDEX 1640
#define LLC_ILLEGAL_TIMER_NAME 1650
#define LLC_UNKNOWN_TIMER_DESIGNATION 1660
#define LLC_ILLEGAL_DATALINK_NAME 1670
#define LLC_ILLEGAL_NETWORK_NAME 1675
#define LLC_UNKNOWN_LINK_DESIGNATION 1680
#define LLC_ILLEGAL_DATALINK_INDEX 1690
#define LLC_ABS_FILENAME_TOO_LONG 1700
#define LLC_ILLEGAL_SEARCHPATH 1710
#define LLC_CONFIG_FILE_NOT_FOUND 1720
#define LLC_FAILED_TO_OPEN_FILE 1730
#define LLC_NETWORK_ARRAY_TOO_SMALL 1740
#define LLC_UNKNOWN_NODE_TYPE_REQUESTED 1800
#define LLC_UNSUPPORTED_PARAMETER 1810
#define LLC_NODE_SETUP_IMPOSSIBLE 1820
#define LLC_NODE_ALLOCATION_FAILED 1830
#define LLC_NETWORK_NODE_NOT_FOUND 1840
#define LLC_UNKNOWN_NODE_TYPE_ENCOUNTERED 1850
#define LLC_NETWORK_NODE_SPACE_EXHAUSTED 1860
#define LLC_SOURCE_NODE_UNDEFINED 1870
#define LLC_DISCARDING_FOREIGN_NODE 1880
#define LLC_FAILED_TO_ENQUEUE_NETWORK 1890
#define LLC_UNRECOGNISED_DATE_FORMAT 1900
#define LLC_UNRECOGNISED_TIME_FORMAT 1910
#define LLC_DATE_OUT_OF_RANGE 1920
#define LLC_TARGET_NODE_UNDEFINED 1930
#define LLC_SIGNAL_HANDLER_PRESENT 2000
#define LLC_FAILED_CHANGING_SIGNAL_ACTION 2010
#define LLC_FAILED_CHANGING_SIGNAL_MASK 2020
#define LLC_ILLEGAL_REALTIME_SIGNAL 2030
#define LLC_FAILED_TO_RESTORE_SIGMASK 2040
#define LLC_RT_SIGNAL_DELIVERY_FAILED 2050
#define LLC_SENDING_RT_SIGNAL_FAILED 2060
#define LLC_NO_SIGNAL_HANDLER_PRESENT 2070
#define LLC_NETWORK_WAKEUP_INCOMPLETE 2080
#define LLC_NETWORK_LAUNCH_INCOMPLETE 2090
#define LLC_NETWORK_RUNNING_ALREADY 2100
#define LLC_ILLEGAL_THREAD_PRIORITY 2110
#define LLC_FAILED_TO_SET_THREAD_PRIORITY 2120
#define LLC_ILLEGAL_THREADING_POLICY 2130
#define LLC_FAILED_TO_START_NETWORK_OPERATOR 2140
#define LLC_NETWORK_OPERATOR_NOT_JOINABLE 2150
#define LLC_MEMORY_LOCKING_FAILED 2160
#define LLC_STOP_SIGNAL_HANDLER_PRESENT 2170
#define LLC_FAILED_TO_START_LOGGER 2180
#define LLC_LOGGER_NO_LONGER_RUNNING 2190
#define LLC_LOG_BUFFER_OVERRUN 2200
#define LLC_OUTPUT_BUFFER_EXHAUSTED 2250
#define LLC_NETWORK_ALLOCATION_FAILED 2300
#define LLC_UNKNOWN_NETWORK_TYPE_REQUESTED 2310
#define LLC_NO_MORE_LANES_AVAILABLE 2320
#define LLC_OUTBOUND_CHANNELS_EXHAUSTED 2330
#define LLC_NO_MORE_NETWORKLINKS_AVAILABLE 2340
#define LLC_INVALID_NETLINK_CONFIGURATION 2350
#define LLC_INVALID_DATA_LANE_INDEX 2360
#define LLC_TARGET_NETWORK_UNDEFINED 2370
#define LLC_DATALINK_WIDTH_MISMATCH 2380
#define LLC_INOPERABLE_DATALINK_FOUND 2390
#define LLC_DUPLICATE_DOWNLINK_DEFINITION 2400
#define LLC_DUPLICATE_UPLINK_DEFINITION 2410
#define LLC_INCOMPATIBLE_PLUGIN_VERSION 2500
#define LLC_FAILED_TO_LOAD_PLUGIN 2510
#define LLC_FAILED_TO_RESOLVE_SYMBOLS 2520
#define LLC_OBJECT_TYPE_NOT_REGISTERED 2530
#define LLC_PLUGIN_DIRECTORY_NOT_FOUND 2540
#define LLC_NO_PLUGINS_LOADED 2550
#define LLC_MESSAGE_BUFFER_TOO_SHORT 2600
#define LLC_MESSAGE_QUEUE_FULL 2610
#define LLC_WRITING_UNDEFINED_DATA_TYPE 3000
#define LLC_READING_UNDEFINED_DATA_TYPE 3010
#define LLC_SOCKETRUNNER_LAUNCHED_ALREADY 3100
#define LLC_FAILED_TO_START_SOCKETRUNNER 3110
#define LLC_SOCKETRUNNER_NOT_JOINABLE 3120
#define LLC_SOCKETRUNNER_ALREADY_ASSIGNED 3130
#define LLC_DATA_STACK_OVERFLOW 3200
#define LLC_DATA_STACK_EMPTY 3210
#define LLC_UNDEFINED_TOKEN_ENCOUNTERED 3220
#define LLC_NO_SPACE_LEFT_IN_DATASTORE 3230
#define LLC_INCONSISTENT_ARRAY_DATA 3240
#define LLC_DATA_STORE_CORRUPTED 3250
#define LLC_DATA_STORE_EMPTY 3260
#define LLC_UNDEFINED_OPTION 3300
#define LLC_ILLEGAL_CMDLINE_PARAM 3310

#define LLC_MAX_FILE_PATH_LENGTH 1024
#define LLC_OPERAND_STACK 128             // NMEA messages must not have
#define LLC_MAX_MESSAGE_LENGTH 384        // more than 82 characters ...
#define LLC_SIZE_MESSAGE_QUEUE 256
#define LLC_IPV4_BUFFER_LENGTH 16         // 4 blocks of 3 digits each ...
#define LLC_MAX_NAME_LENGTH 32
#define LLC_MAX_NUMBER_OF_TIMERS 16
#define LLC_MAX_NUMBER_OF_LANES 64
#define LLC_MAX_NUMBER_OF_NETLINKS 8
#define LLC_MAX_NUMBER_OF_CHANNELS 256
#define LLC_MAX_NUMBER_OF_NETWORKS 4
#define LLC_MAX_NODE_COUNT 64
#define LLC_MAX_ERROR_LOG_SIZE 256
#define LLC_MAX_INCIDENT_COUNT 24
#define LLC_MAX_RTSIGNAL_NUMBER 128       // this is a safe upper limit

// #define LLC_RUNNING_REALTIME_KERNEL    // define this to enable network
//                                        // thread reprioritization
//                                        // CMake option (default: ON) ...

#define LLC_DEFAULT_POLICY SCHED_RR       // real-time scheduling policy

enum SocketType { SIO, SIO_BUFFERED,      // Serial interface w/o buffer
                  TCP, TCP_BUFFERED,      // TCP connection w/o buffer
                  UDP, UDP_BUFFERED,      // UDP protocol w/o buffers
                  TCP_SERVER } ;          // TCP server socket / listener

#define LLC_NO_DEBUG_INFORMATION   0      // These numbers are used to
#define LLC_NO_PROGRESS_REPORTS    2      // control the verbosity of
#define LLC_FULL_PROGRESS_REPORT   8      // the parser log

#define LLC_ILLFORMED_CONFIGURATION_FILE   0x00001  // These flags are
#define LLC_UNKNOWN_NODE_IDENTIIFER        0x00002  // used by the
#define LLC_UNDEFINED_INPUT_CHANNEL_USED   0x00004  // configuration file
#define LLC_UNDEFINED_OUTPUT_CHANNEL_USED  0x00008  // parser to indicate
#define LLC_UNDEFINED_NODE_ENCOUNTERED     0x00010  // error conditions
#define LLC_TIMER_CONNECTION_FAILURE       0x00020  // it has encountered
#define LLC_NODE_CONNECTION_FAILURE        0x00040
#define LLC_DUPLICATE_NODE_SPECIFICATION   0x00080
#define LLC_NODE_IDENTIIFER_MISSING        0x00100
#define LLC_ILLEGAL_NODE_PARAMETER_USED    0x00200
#define LLC_TIMER_ALLOCATION_FAILED        0x00400
#define LLC_TIMER_INTERVAL_UNSPECIFIED     0x00800
#define LLC_ILLEGAL_DATE_FORMAT_USED       0x01000
#define LLC_ILLEGAL_TIME_FORMAT_USED       0x02000
#define LLC_INCOMPLETE_DATA_FOR_SETUP      0x04000
#define LLC_MEMORY_ALLOCATION_PROBLEM      0x08000
#define LLC_TOO_MANY_NETWORKS_DEFINED      0x10000
#define LLC_LINK_CONNECTION_FAILURE        0x20000
#define LLC_LINK_CONFIGURATION_ERROR       0x40000
#define LLC_LINK_ALLOCATION_FAILURE        0x80000

#define LLC_MINIMAL_SELECT_BACKOFF 500000       // 0.5ms backoff @ start

#define LLC_SIZE_OF_TOKEN_STACK   4096
#define LLC_SIZE_OF_DATA_STACK      16          // Size of both buffers
#define LLC_SIZE_OF_DATA_STORE     256          // given in kilobytes!

#define LLC_CONFIG_SEARCHPATH "LLC_CONFIG_SEARCH_PATH"
#define LLC_PLUGIN_DIRECTORY  "LLC_PLUGIN_DIRECTORY"

#endif     // __LOWLAT_CONV_DEFINES_H
