# Configuration for the Windows Packaging System (WIX):

SET( CPACK_GENERATOR "WIX" )
SET( CPACK_WIX_PROGRAM_MENU_FOLDER "CmdLine" )
SET( CPACK_WIX_CULTURES "en-us" )

SET( CPACK_WIX_CMAKE_PACKAGE_REGISTRY "CmdLine" )

SET( CPACK_WIX_SKIP_PROGRAM_FOLDER OFF )

SET( CPACK_WIX_ROOT_FEATURE_TITLE "CmdLine Library" )

SET( CPACK_WIX_ROOT_FEATURE_DESCRIPTION
     "A simple, portable command line parser written in C++" )

SET( CPACK_WIX_UPGRADE_GUID "D3362EF1-37C0-478C-AFBA-1340FDDFFAD1" )
SET( CPACK_WIX_PRODUCT_GUID "3270DBB9-4165-4AF1-A4C5-7BA5206F7E06" )

SET( CPACK_WIX_LICENSE_RTF "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.rtf" )

# CPACK_WIX_ROOT
# CPACK_WIX_PRODUCT_ICON
# CPACK_WIX_UI_REF
# CPACK_WIX_UI_BANNER
# CPACK_WIX_UI_DIALOG
# CPACK_WIX_TEMPLATE
# CPACK_WIX_PATCH_FILE
# CPACK_WIX_EXTRA_SOURCES
# CPACK_WIX_EXTRA_OBJECTS
# CPACK_WIX_EXTENSIONS



# The following list contains some example properties that can be used to customize information under "Add or Remove Programs":

#CPACK_WIX_PROPERTY_ARPCOMMENTS - Comments
#CPACK_WIX_PROPERTY_ARPHELPLINK - Help and support information URL
#CPACK_WIX_PROPERTY_ARPURLINFOABOUT - General information URL
#CPACK_WIX_PROPERTY_ARPURLUPDATEINFO - Update information URL
#CPACK_WIX_PROPERTY_ARPHELPTELEPHONE - Help and support telephone number
#CPACK_WIX_PROPERTY_ARPSIZE - Size (in kilobytes) of the application

# CPACK_WIX_ROOT_FOLDER_ID

# CPACK_WIX_CUSTOM_XMLNS
# CPACK_WIX_SKIP_WIX_UI_EXTENSION