
# Configuration to create a "CmdLine" Debian package ...

SET( CPACK_GENERATOR "DEB" )
SET( CPACK_DEB_COMPONENT_INSTALL ON )

STRING( TOUPPER "${LIBNAME}_Development" DEVCOMP )
STRING( TOUPPER "${LIBNAME}_Runtime" RTCOMP )

SET( CPACK_DEBIAN_${RTCOMP}_PACKAGE_NAME "cmdline" )
SET( CPACK_DEBIAN_${RTCOMP}_FILE_NAME DEB-DEFAULT )
SET( CPACK_DEBIAN_${DEVCOMP}_PACKAGE_NAME "cmdline-dev" )
SET( CPACK_DEBIAN_${DEVCOMP}_FILE_NAME DEB-DEFAULT )

## SET( CPACK_DEBIAN_PACKAGE_EPOCH 1 )

OPTION( CPACK_DEBIAN_PACKAGE_DEBUG 
        "Trace activities of the package generator."
        OFF
)
OPTION( CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS
        "Generate shlibs control file automatically."
        ON
)

SET( CPACK_PACKAGE_DESCRIPTION_SUMMARY 
     "A simple, portable command line parser written in C++11." )

##SET( CPACK_DEBIAN_PACKAGE_NAME "cmdline" )
SET( CPACK_DEBIAN_PACKAGE_PRIORITY "extra" )

SET( CPACK_PACKAGE_VENDOR "Hinderk Buss" )
SET( CPACK_PACKAGE_CONTACT "Hinderk Buss" )
SET( CPACK_DEBIAN_PACKAGE_MAINTAINER "Hinderk Buss" )
SET( CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/Hinderk/cmdline" )
 
SET( CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/INFO.md" )
SET( CPACK_PACKAGE_LICENSE_FILE "${CMAKE_SOURCE_DIR}/LICENSE" )


SET( CPACK_DEBIAN_PACKAGE_DEPENDS "libc6, libstdc++6" )

IF( CMDLINE_SEPARATE_DEBUG_SYMBOLS )
  SET( CPACK_DEBIAN_${RTCOMP}_DEBUGINFO_PACKAGE YES )
ENDIF()


##############################################################################


#CPACK_DEBIAN_FILE_NAME
#CPACK_DEBIAN_PACKAGE_VERSION
#CPACK_DEBIAN_PACKAGE_RELEASE
#CPACK_DEBIAN_PACKAGE_ARCHITECTURE


### CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS
#CPACK_DEBIAN_PACKAGE_PREDEPENDS
#CPACK_DEBIAN_PACKAGE_ENHANCES
#CPACK_DEBIAN_PACKAGE_BREAKS
#CPACK_DEBIAN_PACKAGE_CONFLICTS
#CPACK_DEBIAN_PACKAGE_PROVIDES
#CPACK_DEBIAN_PACKAGE_REPLACES
#CPACK_DEBIAN_PACKAGE_RECOMMENDS
#CPACK_DEBIAN_PACKAGE_SUGGESTS
#CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY
#CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
#CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION
#CPACK_DEBIAN_DEBUGINFO_PACKAGE
